# Generated by Django 4.1.3 on 2023-01-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_type_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
    ]
