# Generated by Django 4.1.3 on 2023-01-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_custom_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
