# Generated by Django 4.1.3 on 2023-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_custom_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
