# Generated by Django 4.1.3 on 2023-01-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_custom_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='image',
            field=models.ImageField(blank=True, default='abstract-user.png', null=True, upload_to=''),
        ),
    ]
