# Generated by Django 4.1.3 on 2023-01-17 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_type_alter_message_sender'),
        ('user', '0005_alter_custom_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='chats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
